
repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        types: [python]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
    -   id: ruff
        types: [python]
    -   id: ruff-format
        types: [python]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
